# Generated by Django 5.2.1 on 2025-05-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('By_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(verbose_name='زمان پایان رأی\u200cگیری')),
            ],
        ),
    ]
